apiVersion: v1
kind: Service
metadata:
  name: image-upload-load-balancer
spec:
  selector:
    app: image-upload-pod
  ports:
    - port: 8003
      targetPort: 8003
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-upload-deployment
spec:
  selector:
    matchLabels:
      app: image-upload-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: image-upload-pod
    spec:
      containers:
        - name: image-upload-container
          image: image-upload:v1
          imagePullPolicy: Never
          resources:
            limits:
              memory: "512M"
              cpu: "300m"
            requests:
              memory: "200M"
              cpu: "150m"
          ports:
            - containerPort: 8003
